POST http://localhost/pokemons
Content-Type: application/json

{
    "pokemon_id" : 1,
    "nickname": "testing"
}

###
GET http://localhost/pokemons

###
GET http://localhost/pokemons?offset=2&limit=2

###
PATCH http://localhost/pokemons/2
Content-Type: application/json

###
DELETE http://localhost/pokemons/release/1

###
GET http://localhost/pokemons/saurs